# Generated by Django 4.1 on 2022-08-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertDetial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alertName', models.CharField(max_length=200)),
                ('alertInterestedParty', models.CharField(max_length=200)),
                ('variations', models.CharField(max_length=500)),
                ('active', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='FileAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=200)),
                ('alertName', models.CharField(max_length=200)),
                ('alertDesc', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='IncomingFileMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=200)),
                ('arrivalTime', models.DateTimeField(auto_now_add=True)),
                ('size', models.IntegerField(default=0)),
                ('sender', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=200)),
                ('arrivalTime', models.DateTimeField(auto_now_add=True)),
                ('sender', models.CharField(max_length=200)),
            ],
        ),
    ]
